### ISSUE TITLE
Missing wheels for macos/arm64

### ISSUE THREAD

**Issue by leonardt** [Kuree/uinspect#2]
Need for pip install support on M-series devices, looks like github actions is supporting it via a public beta https://github.com/github/roadmap/issues/528

**Comment by leonardt** [comment]
Actually the wording on that issue is a bit confusing, perhaps it's meant to serve as an announcement for a planned feature?

**Comment by leonardt** [comment]
One option might be cross-compiling for arm using xcode: https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary

**Comment by leonardt** [comment]
This looks useful: https://github.com/pypa/cibuildwheel

**Comment by Kuree** [comment]
I don't have access to macos or M-series devices so it would be hard for me to test, but I'm happy to try out `cibuildwheel` tonight and see if it works. If you beat me to it, feel free to send a PR.

**Comment by leonardt** [comment]
Confirmed working for M1 mac
